In [1]:
# install mdtraj
%pip install mdtraj
import mdtraj as md
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
# load the pdb file 
traj = md.load_pdb('../Data/1UBQ_processed.pdb')

In [3]:
# get total number of hydrogen bonds
hbonds = md.baker_hubbard(traj)
print(hbonds)

[[   0    3  285]
 [  36   37  254]
 [  55   56 1044]
 [  75   76  221]
 [  91   92 1077]
 [ 113  114  188]
 [ 146  147  119]
 [ 160  161  126]
 [ 203  204   90]
 [ 236  237   54]
 [ 270  271   18]
 [ 286  287  335]
 [ 326  327  300]
 [ 352  353  869]
 [ 371  372  838]
 [ 386  387  344]
 [ 386  387  351]
 [ 400  401  351]
 [ 416  417  370]
 [ 432  434  836]
 [ 438  439  385]
 [ 448  449  399]
 [ 464  466  269]
 [ 470  471  415]
 [ 489  490  437]
 [ 506  507  447]
 [ 518  519  469]
 [ 540  541  488]
 [ 555  556  505]
 [ 621  622  594]
 [ 638  639  608]
 [ 650  651  580]
 [ 650  652  437]
 [ 655  656 1129]
 [ 668  669  788]
 [ 698  699 1094]
 [ 717  718  775]
 [ 754  755  736]
 [ 793  794  697]
 [ 812  813  939]
 [ 846  847  826]
 [ 870  871  922]
 [ 884  885  337]
 [ 903  904  314]
 [ 914  915  876]
 [ 914  915  883]
 [ 926  927  902]
 [ 947  948  913]
 [ 961  962  902]
 [1019 1020   35]
 [1034 1035  996]
 [1059 1060   74]
 [1078 1079  716]
 [1095 1096  112]
 [1114 1115  678]
 [1149 115

In [19]:
# compute the number of helical amino acids
h_amino_acids = md.compute_dssp(traj, simplified=True)
print(h_amino_acids)

[['C' 'E' 'E' 'E' 'E' 'E' 'E' 'C' 'C' 'C' 'C' 'E' 'E' 'E' 'E' 'E' 'C' 'C'
  'C' 'C' 'C' 'E' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'C' 'C'
  'C' 'H' 'H' 'H' 'E' 'E' 'E' 'E' 'E' 'C' 'C' 'E' 'E' 'C' 'C' 'C' 'C' 'C'
  'E' 'C' 'H' 'H' 'H' 'C' 'C' 'C' 'C' 'C' 'C' 'E' 'E' 'E' 'E' 'E' 'E' 'C'
  'C' 'C' 'C' 'C' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA'
  'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA'
  'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA'
  'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA' 'NA'
  'NA' 'NA' 'NA' 'NA' 'NA']]
